// ============================================================
// POKEMON TCG - Editable Stats File
// ============================================================
// This file contains Pokemon and Item base stats for easy
// proofing and editing. Types, weaknesses, resistances, HP,
// and cost can be tweaked here.
//
// Attacks and abilities are NOT stored here -- they remain
// in battle-system.html.
// ============================================================

window.POKEMON_DATA = [
  { name: "Alolan Ninetales",   types: ["Ice", "Fairy"],          cost: 4, hp: 190, weakness: ["Rock", "Poison"],       resistance: ["Dragon", "Ice"] },
  { name: "Alolan Raichu",      types: ["Electric", "Psychic"],   cost: 4, hp: 150, weakness: ["Ground", "Dark"],       resistance: ["Steel", "Psychic"] },
  { name: "Arceus",             types: ["Normal"],                cost: 6, hp: 300, weakness: [],                        resistance: ["Ghost"] },
  { name: "Archeops",           types: ["Rock", "Flying"],        cost: 5, hp: 240, weakness: ["Steel", "Ice"],          resistance: ["Flying", "Ground"] },
  { name: "Arctozolt",          types: ["Electric", "Ice"],       cost: 4, hp: 230, weakness: ["Ground", "Rock"],        resistance: ["Steel", "Ice"] },
  { name: "Baxcalibur",         types: ["Dragon", "Ice"],         cost: 5, hp: 260, weakness: ["Dragon", "Rock"],        resistance: ["Grass", "Ice"] },
  { name: "Beedrill",           types: ["Bug", "Poison"],         cost: 3, hp: 180, weakness: ["Fire", "Psychic"],       resistance: ["Fighting", "Bug"] },
  { name: "Chansey",            types: ["Normal"],                cost: 4, hp: 320, weakness: [],                        resistance: ["Ghost"] },
  { name: "Charizard",          types: ["Fire", "Flying"],        cost: 4, hp: 200, weakness: ["Water", "Ice"],          resistance: ["Fairy", "Ground"] },
  { name: "Clodsire",           types: ["Poison", "Ground"],      cost: 3, hp: 240, weakness: ["Psychic", "Grass"],      resistance: ["Bug", "Electric"] },
  { name: "Delibird",           types: ["Ice", "Flying"],         cost: 2, hp: 120, weakness: ["Rock"],                  resistance: ["Ground"] },
  { name: "Ditto",              types: ["Normal"],                cost: 2, hp: 130, weakness: [],                        resistance: ["Ghost"] },
  { name: "Drednaw",            types: ["Water", "Rock"],         cost: 4, hp: 200, weakness: ["Electric", "Steel"],     resistance: ["Fire", "Flying"] },
  { name: "Eevee",              types: ["Normal"],                cost: 2, hp: 150, weakness: [],                        resistance: ["Ghost"] },
  { name: "Entei",              types: ["Fire"],                  cost: 5, hp: 250, weakness: ["Water"],                 resistance: ["Fairy"] },
  { name: "Flareon",            types: ["Fire"],                  cost: 4, hp: 200, weakness: ["Water"],                 resistance: ["Fairy"] },
  { name: "Flygon",             types: ["Ground", "Dragon"],      cost: 4, hp: 200, weakness: ["Dragon"],                resistance: ["Electric"] },
  { name: "Galarian Weezing",   types: ["Poison", "Fairy"],       cost: 4, hp: 210, weakness: ["Psychic", "Poison"],     resistance: ["Bug", "Dragon"] },
  { name: "Gengar",             types: ["Ghost", "Poison"],       cost: 4, hp: 180, weakness: ["Ghost", "Psychic"],      resistance: ["Normal", "Bug"] },
  { name: "Glaceon",            types: ["Ice"],                   cost: 4, hp: 230, weakness: ["Rock"],                  resistance: ["Ice"] },
  { name: "Golisopod",          types: ["Bug", "Water"],          cost: 4, hp: 260, weakness: ["Electric"],              resistance: ["Fighting"] },
  { name: "Gothorita",          types: ["Psychic"],               cost: 3, hp: 210, weakness: ["Dark"],                  resistance: ["Psychic"] },
  { name: "Groudon",            types: ["Ground"],                cost: 6, hp: 300, weakness: ["Grass"],                 resistance: ["Electric"] },
  { name: "Guzzlord",           types: ["Dark", "Dragon"],        cost: 5, hp: 300, weakness: ["Fairy", "Dragon"],       resistance: ["Dark", "Grass"] },
  { name: "Gyarados",           types: ["Water", "Flying"],       cost: 4, hp: 230, weakness: ["Electric", "Ice"],       resistance: ["Fire", "Ground"] },
  { name: "Hitmontop",          types: ["Fighting"],              cost: 4, hp: 250, weakness: ["Flying"],                resistance: ["Rock"] },
  { name: "Kartana",            types: ["Grass", "Steel"],        cost: 5, hp: 210, weakness: ["Bug", "Fighting"],       resistance: ["Water", "Poison"] },
  { name: "Koraidon",           types: ["Fighting", "Dragon"],    cost: 6, hp: 290, weakness: ["Flying", "Dragon"],      resistance: ["Rock", "Grass"] },
  { name: "Kricketune",         types: ["Bug"],                   cost: 3, hp: 170, weakness: ["Fire"],                  resistance: ["Fighting"] },
  { name: "Kyogre",             types: ["Water"],                 cost: 6, hp: 300, weakness: ["Electric"],              resistance: ["Fire"] },
  { name: "Lucario",            types: ["Fighting", "Steel"],     cost: 4, hp: 180, weakness: ["Flying", "Fighting"],    resistance: ["Poison", "Rock"] },
  { name: "Lycanroc",           types: ["Rock"],                  cost: 4, hp: 210, weakness: ["Steel"],                 resistance: ["Flying"] },
  { name: "Marowak",            types: ["Ground"],                cost: 3, hp: 200, weakness: ["Grass"],                 resistance: ["Electric"] },
  { name: "Mawile",             types: ["Steel", "Fairy"],        cost: 3, hp: 180, weakness: ["Fighting"],              resistance: ["Dragon"] },
  { name: "Medicham",           types: ["Fighting", "Psychic"],   cost: 3, hp: 190, weakness: ["Flying", "Dark"],        resistance: ["Rock", "Psychic"] },
  { name: "Mega Absol",         types: ["Dark"],                  cost: 5, hp: 190, weakness: ["Fairy"],                 resistance: ["Dark"] },
  { name: "Mega Absol Z",       types: ["Dark", "Psychic"],       cost: 5, hp: 190, weakness: ["Fairy"],                 resistance: ["Psychic"] },
  { name: "Mega Aggron",        types: ["Steel"],                 cost: 5, hp: 310, weakness: ["Fighting"],              resistance: ["Poison"] },
  { name: "Mega Audino",        types: ["Normal", "Fairy"],       cost: 4, hp: 260, weakness: ["Poison"],                resistance: ["Ghost", "Dragon"] },
  { name: "Mega Blaziken",      types: ["Fire", "Fighting"],      cost: 5, hp: 210, weakness: ["Water", "Flying"],       resistance: ["Fairy", "Rock"] },
  { name: "Mega Mewtwo X",      types: ["Psychic", "Fighting"],   cost: 7, hp: 270, weakness: ["Dark", "Flying"],        resistance: ["Psychic", "Rock"] },
  { name: "Meowth",             types: ["Normal"],                cost: 2, hp: 130, weakness: [],                        resistance: ["Ghost"] },
  { name: "Mew",                types: ["Psychic"],               cost: 5, hp: 230, weakness: ["Dark"],                  resistance: ["Psychic"] },
  { name: "Mewtwo",             types: ["Psychic"],               cost: 6, hp: 250, weakness: ["Dark"],                  resistance: ["Psychic"] },
  { name: "Mismagius",          types: ["Ghost"],                 cost: 4, hp: 200, weakness: ["Ghost"],                 resistance: ["Normal"] },
  { name: "Muk",                types: ["Poison"],                cost: 4, hp: 250, weakness: ["Psychic"],               resistance: ["Bug"] },
  { name: "Obstagoon",          types: ["Dark", "Normal"],        cost: 4, hp: 230, weakness: ["Fairy"],                 resistance: ["Ghost", "Dark"] },
  { name: "Oinkologne",        types: ["Normal"],                cost: 4, hp: 240, weakness: [],                        resistance: ["Ghost"] },
  { name: "Pichu",              types: ["Electric"],              cost: 1, hp:  80, weakness: ["Ground"],                resistance: ["Steel"] },
  { name: "Psyduck",            types: ["Water"],                 cost: 2, hp: 140, weakness: ["Electric"],              resistance: ["Fire"] },
  { name: "Raikou",             types: ["Electric"],              cost: 5, hp: 240, weakness: ["Ground"],                resistance: ["Steel"] },
  { name: "Regigigas",          types: ["Normal"],                cost: 6, hp: 330, weakness: [],                        resistance: ["Ghost"] },
  { name: "Reshiram",           types: ["Dragon", "Fire"],        cost: 6, hp: 280, weakness: ["Water", "Dragon"],       resistance: ["Fairy", "Grass"] },
  { name: "Rhydon",             types: ["Ground", "Rock"],        cost: 4, hp: 250, weakness: ["Grass", "Steel"],        resistance: ["Electric", "Flying"] },
  { name: "Sceptile",           types: ["Grass"],                 cost: 4, hp: 190, weakness: ["Bug"],                   resistance: ["Water"] },
  { name: "Scovillain",         types: ["Grass", "Fire"],         cost: 4, hp: 180, weakness: ["Bug"],                   resistance: ["Fairy"] },
  { name: "Shedinja",           types: ["Bug", "Ghost"],          cost: 1, hp:  60, weakness: ["Fire", "Ghost"],         resistance: ["Fighting", "Normal"] },
  { name: "Shuckle",            types: ["Bug", "Rock"],           cost: 4, hp: 300, weakness: ["Fire", "Steel"],         resistance: ["Fighting", "Flying"] },
  { name: "Skarmory",           types: ["Steel", "Flying"],       cost: 4, hp: 260, weakness: ["Fighting", "Ice"],       resistance: ["Poison", "Ground"] },
  { name: "Slurpuff",           types: ["Fairy"],                 cost: 4, hp: 230, weakness: ["Poison"],                resistance: ["Dragon"] },
  { name: "Snorlax",            types: ["Normal"],                cost: 4, hp: 270, weakness: [],                        resistance: ["Ghost"] },
  { name: "Sudowoodo",          types: ["Rock"],                  cost: 3, hp: 220, weakness: ["Steel"],                 resistance: ["Flying"] },
  { name: "Suicune",            types: ["Water"],                 cost: 5, hp: 280, weakness: ["Electric"],              resistance: ["Fire"] },
  { name: "Sylveon",            types: ["Fairy"],                 cost: 4, hp: 250, weakness: ["Poison"],                resistance: ["Dragon"] },
  { name: "Trevenant",          types: ["Grass", "Ghost"],        cost: 4, hp: 230, weakness: ["Bug", "Ghost"],          resistance: ["Normal", "Water"] },
  { name: "Umbreon",            types: ["Dark"],                  cost: 4, hp: 280, weakness: ["Fairy"],                 resistance: ["Dark"] },
  { name: "Unown",              types: ["Psychic"],               cost: 2, hp: 130, weakness: ["Dark"],                  resistance: ["Psychic"] },
  { name: "Vileplume",          types: ["Grass", "Poison"],       cost: 4, hp: 200, weakness: ["Psychic"],               resistance: ["Water"] },
  { name: "Zeraora",            types: ["Electric"],              cost: 5, hp: 220, weakness: ["Ground"],                resistance: ["Steel"] },
  { name: "Zoroark",            types: ["Dark", "Normal"],        cost: 4, hp: 170, weakness: ["Fairy"],                 resistance: ["Dark", "Ghost"] },
  { name: "Zorua",              types: ["Dark", "Normal"],        cost: 2, hp: 110, weakness: ["Fairy"],                 resistance: ["Dark", "Ghost"] },
];

window.ITEM_DATA = [
  { name: "Assault Vest",    desc: "-20 damage taken",            key: "assaultVest" },
  { name: "Burn Scarf",      desc: "Attacked: 10 dmg + Burn",     key: "burnScarf" },
  { name: "Expert Belt",     desc: "2x weakness (not 1.5x)",      key: "expertBelt" },
  { name: "Filter Shield",   desc: "Immune to resisted types",    key: "filterShield" },
  { name: "Float Stone",     desc: "Quick Retreat -1 energy",     key: "floatStone" },
  { name: "Focus Sash",      desc: "Survive KO at 10 HP",        key: "focusSash",      oneTime: true },
  { name: "Health Charm",    desc: "+50 HP",                      key: "healthCharm" },
  { name: "Healing Scarf",   desc: "Heal 20 per energy gained",   key: "healingScarf" },
  { name: "Leftovers",       desc: "Heal 10 per turn",            key: "leftovers" },
  { name: "Life Orb",        desc: "+30 damage, 10 recoil",       key: "lifeOrb" },
  { name: "Loud Bell",       desc: "Attacked: 10 dmg + Confuse",  key: "loudBell" },
  { name: "Lucky Punch",     desc: "50%: +20 dmg + Normal weak",  key: "luckyPunch" },
  { name: "Lum Berry",       desc: "Cure status + heal 30",       key: "lumBerry",       oneTime: true },
  { name: "Muscle Band",     desc: "+20 damage",                  key: "muscleBand" },
  { name: "Pierce Scope",    desc: "Normal=weak to your type",    key: "pierceScope" },
  { name: "Poison Barb",     desc: "Attacked: 10 dmg + Poison",   key: "poisonBarb" },
  { name: "Power Herb",      desc: "Deploy: +1 energy",           key: "powerHerb",      oneTime: true },
  { name: "Protect Goggles", desc: "Block non-dmg effects",       key: "protectGoggles" },
  { name: "Quick Claw",      desc: "1st attack -2 energy",        key: "quickClaw",      oneTime: true },
  { name: "Rescue Scarf",    desc: "Return to hand on KO",        key: "rescueScarf" },
  { name: "Rocky Helmet",    desc: "Attacked: 30 dmg back",       key: "rockyHelmet" },
  { name: "Shell Bell",      desc: "Heal 30 when attacking",      key: "shellBell" },
  { name: "Sitrus Berry",    desc: "At 100+ dmg: heal 60",        key: "sitrusBerry",    oneTime: true },
  { name: "White Herb",      desc: "Prevent 2 energy loss",       key: "whiteHerb",      oneTime: true },
  { name: "Wide Shield",     desc: "Active: team -10 dmg",        key: "wideShield" },
];
